export const QMK_KEYCODE_MAP: Record<string, string> = {
  KC_A: 'A',
  KC_B: 'B',
  KC_C: 'C',
  KC_D: 'D',
  KC_E: 'E',
  KC_F: 'F',
  KC_G: 'G',
  KC_H: 'H',
  KC_I: 'I',
  KC_J: 'J',
  KC_K: 'K',
  KC_L: 'L',
  KC_M: 'M',
  KC_N: 'N',
  KC_O: 'O',
  KC_P: 'P',
  KC_Q: 'Q',
  KC_R: 'R',
  KC_S: 'S',
  KC_T: 'T',
  KC_U: 'U',
  KC_V: 'V',
  KC_W: 'W',
  KC_X: 'X',
  KC_Y: 'Y',
  KC_Z: 'Z',
  KC_1: '1',
  KC_2: '2',
  KC_3: '3',
  KC_4: '4',
  KC_5: '5',
  KC_6: '6',
  KC_7: '7',
  KC_8: '8',
  KC_9: '9',
  KC_0: '0',
  KC_ENTER: 'Enter',
  KC_ESCAPE: 'Esc',
  KC_BSPACE: 'Backspace',
  KC_TAB: 'Tab',
  KC_SPACE: 'Space',
  KC_MINUS: '-',
  KC_EQUAL: '=',
  KC_LBRACKET: '[',
  KC_RBRACKET: ']',
  KC_BSLASH: '\\',
  KC_SCOLON: ';',
  KC_QUOTE: "'",
  KC_GRAVE: '`',
  KC_COMMA: ',',
  KC_DOT: '.',
  KC_SLASH: '/',
  KC_CAPSLOCK: 'Caps Lock',
  KC_F1: 'F1',
  KC_F2: 'F2',
  KC_F3: 'F3',
  KC_F4: 'F4',
  KC_F5: 'F5',
  KC_F6: 'F6',
  KC_F7: 'F7',
  KC_F8: 'F8',
  KC_F9: 'F9',
  KC_F10: 'F10',
  KC_F11: 'F11',
  KC_F12: 'F12',
  KC_PSCREEN: 'Print Screen',
  KC_SCROLLLOCK: 'Scroll Lock',
  KC_PAUSE: 'Pause',
  KC_INSERT: 'Insert',
  KC_HOME: 'Home',
  KC_PGUP: 'Page Up',
  KC_DELETE: 'Delete',
  KC_END: 'End',
  KC_PGDOWN: 'Page Down',
  KC_RIGHT: '→',
  KC_LEFT: '←',
  KC_DOWN: '↓',
  KC_UP: '↑',
  KC_NUMLOCK: 'Num Lock',
  KC_LCTRL: 'Ctrl',
  KC_LSHIFT: 'Shift',
  KC_LALT: 'Alt',
  KC_LGUI: 'Gui',
  KC_RCTRL: 'Ctrl',
  KC_RSHIFT: 'Shift',
  KC_RALT: 'Alt',
  KC_RGUI: 'Gui',
  KC_TRNS: ' ',
  KC_NO: ' ',
  FN_MO13: 'FN13',
  FN_MO23: 'FN23',
  KC_MS_U: 'M↑',
  KC_MS_D: 'M↓',
  KC_MS_L: 'M←',
  KC_MS_R: 'M→',
  KC_BTN1: 'M1',
  KC_WH_U: 'W↑',
  KC_WH_D: 'W↓',
};

export const getHumanKeycode = (keycode: string | number): string => {
  if (typeof keycode === 'number') {
    return ' ';
  }
  return QMK_KEYCODE_MAP[keycode] || keycode;
};
