services:
  dev:
    build:
      context: .
      target: dev
    network_mode: host
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  prod:
    build:
      context: .
      target: prod
    ports:
      - "8080:80"
